
version: "3.7"
services:
  allergen:
    build: .
    image: 953143184104.dkr.ecr.us-east-1.amazonaws.com/alt-allergen:latest
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    labels:
      aws.ecs.fargate.deploy: 1
