const CLEAR_ERROR = "CLEAR_ERROR";
const POPULATE_ERROR = "POPULATE_ERROR";
const GET_RECIPES = "GET_RECIPES";
const GET_RECIPE = "GET_RECIPE";
const GET_ALLERGENS = "GET_ALLERGENS";

export { CLEAR_ERROR, POPULATE_ERROR, GET_RECIPES, GET_ALLERGENS, GET_RECIPE };
