const SET_ERROR = "SET_ERROR";
const SET_RECIPES = "SET_RECIPES";
const SET_RECIPE = "SET_RECIPE";
const SET_ALLERGENS = "SET_ALLERGENS";
const SET_SEARCH_PARAMS = "SET_SEARCH_PARAMS";

export { SET_ERROR, SET_RECIPES, SET_ALLERGENS, SET_SEARCH_PARAMS, SET_RECIPE };
